import type { DuLich } from './typing';

export const LOAI_DIA_DIEM_LABEL: Record<DuLich.ELoaiDiemDen, string> = {
    BIEN: '🏖️ Biển',
    NUI: '⛰️ Núi',
    THANH_PHO: '🏙️ Thành phố',
};

export const DIEM_DEN_MAC_DINH: DuLich.IDiemDen[] = [
    {
        id: 'dd001',
        ten: 'Phú Quốc',
        loai: 'BIEN',
        moTa: 'Đảo ngọc Phú Quốc với bãi biển cát trắng, nước trong xanh và hải sản tươi ngon. Thiên đường du lịch biển hàng đầu Việt Nam.',
        hinhAnh: 'https://images.unsplash.com/photo-1573790387438-4da905039392?w=800',
        diaChi: 'Kiên Giang, Việt Nam',
        rating: 4.8,
        thoiGianThamQuan: 48,
        chiPhiAn: 300000,
        chiPhiLuuTru: 800000,
        chiPhiDiChuyen: 2500000,
        luotXem: 1520,
        isCustom: false,
    },
    {
        id: 'dd002',
        ten: 'Đà Nẵng',
        loai: 'BIEN',
        moTa: 'Thành phố đáng sống nhất Việt Nam với bãi biển Mỹ Khê thơ mộng, cầu Rồng hùng tráng và ẩm thực phong phú.',
        hinhAnh: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800',
        diaChi: 'Đà Nẵng, Việt Nam',
        rating: 4.7,
        thoiGianThamQuan: 72,
        chiPhiAn: 200000,
        chiPhiLuuTru: 600000,
        chiPhiDiChuyen: 1500000,
        luotXem: 2340,
        isCustom: false,
    },
    {
        id: 'dd003',
        ten: 'Hội An',
        loai: 'THANH_PHO',
        moTa: 'Phố cổ Hội An - Di sản Văn hóa Thế giới với những ngôi nhà cổ kính, đèn lồng rực rỡ và ẩm thực đặc sắc.',
        hinhAnh: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=800',
        diaChi: 'Quảng Nam, Việt Nam',
        rating: 4.9,
        thoiGianThamQuan: 24,
        chiPhiAn: 150000,
        chiPhiLuuTru: 500000,
        chiPhiDiChuyen: 200000,
        luotXem: 3120,
        isCustom: false,
    },
    {
        id: 'dd004',
        ten: 'Sa Pa',
        loai: 'NUI',
        moTa: 'Vùng cao Sa Pa với ruộng bậc thang hùng vĩ, đỉnh Fansipan cao nhất Đông Dương và văn hóa dân tộc đa dạng.',
        hinhAnh: 'https://images.unsplash.com/photo-1540611025311-01df3cef54b5?w=800',
        diaChi: 'Lào Cai, Việt Nam',
        rating: 4.6,
        thoiGianThamQuan: 48,
        chiPhiAn: 200000,
        chiPhiLuuTru: 450000,
        chiPhiDiChuyen: 600000,
        luotXem: 1890,
        isCustom: false,
    },
    {
        id: 'dd005',
        ten: 'Hà Nội',
        loai: 'THANH_PHO',
        moTa: 'Thủ đô nghìn năm văn hiến với Hồ Hoàn Kiếm, Văn Miếu - Quốc Tử Giám, phố cổ 36 phố phường và ẩm thực đường phố nổi tiếng.',
        hinhAnh: 'https://images.unsplash.com/photo-1583417667300-f1f4a16e5b55?w=800',
        diaChi: 'Hà Nội, Việt Nam',
        rating: 4.5,
        thoiGianThamQuan: 48,
        chiPhiAn: 180000,
        chiPhiLuuTru: 500000,
        chiPhiDiChuyen: 800000,
        luotXem: 2780,
        isCustom: false,
    },
    {
        id: 'dd006',
        ten: 'TP. Hồ Chí Minh',
        loai: 'THANH_PHO',
        moTa: 'Thành phố sầm uất nhất Việt Nam với bảo tàng lịch sử, chợ Bến Thành, cuộc sống về đêm sôi động và ẩm thực đa dạng.',
        hinhAnh: 'https://images.unsplash.com/photo-1583417267826-aebc4d1542e1?w=800',
        diaChi: 'TP. Hồ Chí Minh, Việt Nam',
        rating: 4.4,
        thoiGianThamQuan: 48,
        chiPhiAn: 200000,
        chiPhiLuuTru: 600000,
        chiPhiDiChuyen: 500000,
        luotXem: 3450,
        isCustom: false,
    },
    {
        id: 'dd007',
        ten: 'Ninh Bình',
        loai: 'NUI',
        moTa: 'Vịnh Hạ Long trên cạn với cảnh quan hang động, núi đá vôi độc đáo, chùa Bái Đính và Tràng An được UNESCO công nhận.',
        hinhAnh: 'https://images.unsplash.com/photo-1559308640-0c4c6dfa9e8a?w=800',
        diaChi: 'Ninh Bình, Việt Nam',
        rating: 4.7,
        thoiGianThamQuan: 24,
        chiPhiAn: 150000,
        chiPhiLuuTru: 350000,
        chiPhiDiChuyen: 400000,
        luotXem: 1450,
        isCustom: false,
    },
    {
        id: 'dd008',
        ten: 'Vịnh Hạ Long',
        loai: 'BIEN',
        moTa: 'Kỳ quan thiên nhiên thế giới với hàng nghìn hòn đảo đá vôi, hang động kỳ bí, làng chài nổi và du thuyền lộng lẫy.',
        hinhAnh: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=800',
        diaChi: 'Quảng Ninh, Việt Nam',
        rating: 4.8,
        thoiGianThamQuan: 48,
        chiPhiAn: 250000,
        chiPhiLuuTru: 1200000,
        chiPhiDiChuyen: 1000000,
        luotXem: 2670,
        isCustom: false,
    },
    {
        id: 'dd009',
        ten: 'Đà Lạt',
        loai: 'NUI',
        moTa: 'Thành phố ngàn hoa với khí hậu mát mẻ quanh năm, rừng thông, hồ Xuân Hương và những vườn dâu tây, rau củ xanh mướt.',
        hinhAnh: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        diaChi: 'Lâm Đồng, Việt Nam',
        rating: 4.6,
        thoiGianThamQuan: 48,
        chiPhiAn: 180000,
        chiPhiLuuTru: 500000,
        chiPhiDiChuyen: 1000000,
        luotXem: 2100,
        isCustom: false,
    },
    {
        id: 'dd010',
        ten: 'Mũi Né',
        loai: 'BIEN',
        moTa: 'Thiên đường khu nghỉ dưỡng biển với đồi cát vàng huyền bí, bãi biển xanh ngắt và các trò chơi thể thao nước hấp dẫn.',
        hinhAnh: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
        diaChi: 'Bình Thuận, Việt Nam',
        rating: 4.3,
        thoiGianThamQuan: 48,
        chiPhiAn: 200000,
        chiPhiLuuTru: 700000,
        chiPhiDiChuyen: 800000,
        luotXem: 1230,
        isCustom: false,
    },
    {
        id: 'dd011',
        ten: 'Huế',
        loai: 'THANH_PHO',
        moTa: 'Cố đô lịch sử với Đại Nội, lăng tẩm các vị vua nhà Nguyễn, chùa Thiên Mụ thơ mộng bên dòng sông Hương.',
        hinhAnh: 'https://images.unsplash.com/photo-1588776813677-77aab5595b83?w=800',
        diaChi: 'Thừa Thiên Huế, Việt Nam',
        rating: 4.5,
        thoiGianThamQuan: 24,
        chiPhiAn: 150000,
        chiPhiLuuTru: 400000,
        chiPhiDiChuyen: 600000,
        luotXem: 1680,
        isCustom: false,
    },
    {
        id: 'dd012',
        ten: 'Côn Đảo',
        loai: 'BIEN',
        moTa: 'Quần đảo thiên đường với nước biển trong vắt, rừng nguyên sinh, rùa biển và lịch sử hào hùng của dân tộc.',
        hinhAnh: 'https://images.unsplash.com/photo-1589308454674-24873b03b0a2?w=800',
        diaChi: 'Bà Rịa - Vũng Tàu, Việt Nam',
        rating: 4.9,
        thoiGianThamQuan: 48,
        chiPhiAn: 350000,
        chiPhiLuuTru: 1500000,
        chiPhiDiChuyen: 3000000,
        luotXem: 980,
        isCustom: false,
    },
];

export const STORAGE_KEYS = {
    DIEM_DEN_CUSTOM: 'DU_LICH__DIEM_DEN_CUSTOM',
    LICH_TRINH: 'DU_LICH__LICH_TRINH',
};

export const HAN_MUC_LABEL: Record<string, string> = {
    an: '🍜 Ăn uống',
    luuTru: '🏨 Lưu trú',
    diChuyen: '🚗 Di chuyển',
    vuiChoi: '🎡 Vui chơi',
    khac: '💼 Khác',
};

export const HAN_MUC_COLOR: Record<string, string> = {
    an: '#FF6B6B',
    luuTru: '#4ECDC4',
    diChuyen: '#45B7D1',
    vuiChoi: '#96CEB4',
    khac: '#FFEAA7',
};
